# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-process
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: order-process
  template:
    metadata:
      labels:
        app: order-process
    spec:
      containers:
      - name: order-process
        image: bhavin1099/orderprocess:v1     
        ports:
        - containerPort: 80