# Backend-Service for Product Catelog
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: product-catelog
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
  type: ClusterIP